name: deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: lti
    runs-on: self-hosted
    steps:
      - name: ssh
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          args: "-tt"
          command: |
            cd /home/OpenDSA/LTI_ruby/
            git pull
